### ISSUE TITLE
Attributes removed from file / error on save file

### ISSUE THREAD

**Issue by onplot** [giscan/Generalizer#2]
Two problems:

Ran remove small objects - resultant file in memory has ID and ELEV attributes set to NULL and two new attributes MYNYM and MYTXT which now carry the ID AND ELEV values - Yes I can update the old attributes but I shouldn't have to as it shouldn't be doing this in the first place.

Secondly, if I click on Browse to save a file I receive the following error:

2020-05-17T14:04:06     WARNING    Traceback (most recent call last):
              File "C:/Users/max/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Generalizer3\generalizerdialog.py", line 343, in outFile
              outFilePath = saveDialog(self)
              File "C:/Users/max/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Generalizer3\dialogs.py", line 14, in saveDialog
              outFilePath, __ = QFileDialog.getSaveFileName(parent, parent.tr('Save output shapefile'), outDir, filter)
             NameError: name 'QFileDialog' is not defined

**Comment by kikislater** [comment]
Thanks for testing. 

Fixed in https://github.com/giscan/Generalizer/pull/3
Will update soon on qgis plugins repository
